### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by FuzzyWuff** [SaphireLattice/noita_unicorn#1]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

happen on the exe from Unicorn_v0.1.0.zip

**Comment by Kavukamari** [comment]
getting same error, not sure what it means

**Comment by SaphireLattice** [comment]
It should be working now, closing as resolved! Please comment and reopen it if problem persists.
